selectMapConfigByUserId ( $vanUserId )
selectDeviceTypeByDeviceId ( $vanDeviceId )
selectDeviceParamByDeviceId ( $vanDeviceId )
selectContractDataByUserId ( $vauiUserId, $vabActive = 0 )
selectMessageByUserId ( $vauiUserId )
insertGpdData ( $vauiDaviceId, $vauiMessageId, $vauiSignalQuality, $vauiPowerControl, $vasGpsDateTime, $vasGpsLatitude, $vasGpsLatitudeHemisphere, $vasGpsLongitude, $vasGpsLongitudeHemisphere, $vasGpsDadaValid )
selectOnConnectMesage ( $vanDeviceId )
selectNormalMessage ( $vanDeviceId )
selectOnDateErroMessage (  $vanDeviceId  )
selectDeviceConfigByDeviceIdAndDeviceType ( $vanDeviceId )
selectLogTxMessageByDeviceId ( $vauiDeviceId )
selectContractAndDevicesByUserId ( $vauiUserId )
selecUserTypeById ( $vauiUserId )